baseURL = 'http://ed.mesihe.org/'
languageCode = 'en-us'
title = 'My New Hugo Site By Ed M'
theme = "anatole"
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/lxndrblz/anatole"
    disable = false
